import jsPDF from 'jspdf'

interface ComplianceReport {
  title: string
  organization: string
  reportType: string
  date: string
  sections: {
    title: string
    content: string | string[]
  }[]
  metadata?: {
    generatedBy?: string
    version?: string
    status?: string
  }
}

export const exportComplianceReportToPDF = (report: ComplianceReport) => {
  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()
  const pageHeight = doc.internal.pageSize.getHeight()
  const margin = 20
  const maxWidth = pageWidth - (margin * 2)
  let yPosition = margin

  // Helper to add new page if needed
  const checkNewPage = (requiredSpace: number = 20) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage()
      yPosition = margin
      return true
    }
    return false
  }

  // Add header with logo placeholder
  doc.setFillColor(30, 64, 175) // Primary blue
  doc.rect(0, 0, pageWidth, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(20)
  doc.text('RegSense Advisor', margin, 25)
  doc.setFontSize(10)
  doc.text('AI-Powered Regulatory Intelligence', margin, 32)
  
  yPosition = 55

  // Report title
  doc.setTextColor(0, 0, 0)
  doc.setFontSize(18)
  doc.text(report.title, margin, yPosition)
  yPosition += 10

  // Organization and metadata
  doc.setFontSize(11)
  doc.setTextColor(100, 100, 100)
  doc.text(`Organization: ${report.organization}`, margin, yPosition)
  yPosition += 7
  doc.text(`Report Type: ${report.reportType}`, margin, yPosition)
  yPosition += 7
  doc.text(`Generated: ${report.date}`, margin, yPosition)
  yPosition += 7

  if (report.metadata?.status) {
    doc.text(`Status: ${report.metadata.status}`, margin, yPosition)
    yPosition += 7
  }

  if (report.metadata?.version) {
    doc.text(`Version: ${report.metadata.version}`, margin, yPosition)
    yPosition += 7
  }

  // Divider line
  yPosition += 5
  doc.setDrawColor(200, 200, 200)
  doc.line(margin, yPosition, pageWidth - margin, yPosition)
  yPosition += 15

  // Report sections
  doc.setTextColor(0, 0, 0)
  
  report.sections.forEach((section, index) => {
    checkNewPage(30)

    // Section title
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.text(section.title, margin, yPosition)
    yPosition += 10

    // Section content
    doc.setFontSize(10)
    doc.setFont('helvetica', 'normal')
    
    if (Array.isArray(section.content)) {
      section.content.forEach((item) => {
        checkNewPage(15)
        const lines = doc.splitTextToSize(`• ${item}`, maxWidth - 10)
        lines.forEach((line: string) => {
          checkNewPage(7)
          doc.text(line, margin + 5, yPosition)
          yPosition += 7
        })
      })
    } else {
      const lines = doc.splitTextToSize(section.content, maxWidth)
      lines.forEach((line: string) => {
        checkNewPage(7)
        doc.text(line, margin, yPosition)
        yPosition += 7
      })
    }

    yPosition += 10
  })

  // Footer on last page
  const totalPages = doc.getNumberOfPages()
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i)
    doc.setFontSize(8)
    doc.setTextColor(150, 150, 150)
    doc.text(
      `Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    )
    doc.text(
      'Generated by RegSense Advisor - Confidential',
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    )
  }

  // Generate filename
  const timestamp = new Date().toISOString().split('T')[0]
  const filename = `${report.reportType}_${report.organization}_${timestamp}.pdf`
    .replace(/[^a-zA-Z0-9_-]/g, '_')

  // Download
  doc.save(filename)
}

// Helper function to format AI Act assessment for PDF
export const formatAIActAssessmentForPDF = (
  assessment: any,
  organizationName: string
): ComplianceReport => {
  return {
    title: 'EU AI Act Compliance Assessment',
    organization: organizationName,
    reportType: 'AI_ACT_AUDIT',
    date: new Date().toLocaleString(),
    metadata: {
      generatedBy: 'AI Act Auditor',
      version: '1.0',
      status: assessment.risk_category || 'Unknown'
    },
    sections: [
      {
        title: 'Executive Summary',
        content: assessment.annex_iv_summary || 'No summary available'
      },
      {
        title: 'Risk Classification',
        content: `Risk Category: ${assessment.risk_category || 'Not classified'}`
      },
      {
        title: 'System Details',
        content: [
          `System Name: ${assessment.system_name || 'N/A'}`,
          `Assessment Date: ${new Date(assessment.created_at).toLocaleString()}`,
          `Conformity Status: ${assessment.conformity_status || 'Pending'}`
        ]
      },
      {
        title: 'Compliance Requirements',
        content: assessment.annex_iv_items 
          ? JSON.parse(assessment.annex_iv_items).map((item: any) => 
              `${item.requirement}: ${item.status}`
            )
          : ['No requirements data available']
      },
      {
        title: 'Evidence Summary',
        content: assessment.evidence_summary || 'No evidence provided'
      },
      {
        title: 'Recommendations',
        content: assessment.recommendations 
          ? assessment.recommendations.split('\n').filter(Boolean)
          : ['No specific recommendations at this time']
      }
    ]
  }
}

// Helper function to format GDPR assessment for PDF
export const formatGDPRAssessmentForPDF = (
  assessment: any,
  organizationName: string
): ComplianceReport => {
  return {
    title: 'GDPR Compliance Assessment',
    organization: organizationName,
    reportType: 'GDPR_CHECK',
    date: new Date().toLocaleString(),
    metadata: {
      generatedBy: 'GDPR Checker',
      version: '1.0',
      status: assessment.violations?.length > 0 ? 'Issues Found' : 'Compliant'
    },
    sections: [
      {
        title: 'Assessment Summary',
        content: assessment.summary || 'No summary available'
      },
      {
        title: 'Violations Detected',
        content: assessment.violations?.length > 0
          ? assessment.violations.map((v: any) => 
              `${v.type}: ${v.description} (Severity: ${v.severity})`
            )
          : ['No violations detected']
      },
      {
        title: 'Personal Data Identified',
        content: assessment.personal_data_found 
          ? assessment.personal_data_found.map((item: string) => item)
          : ['No personal data identified']
      },
      {
        title: 'Recommendations',
        content: assessment.recommendations 
          ? assessment.recommendations.split('\n').filter(Boolean)
          : ['Continue monitoring data processing activities']
      }
    ]
  }
}

// Helper function to format ESG report for PDF
export const formatESGReportForPDF = (
  report: any,
  organizationName: string
): ComplianceReport => {
  return {
    title: 'ESG & CSRD Reporting',
    organization: organizationName,
    reportType: 'ESG_REPORT',
    date: new Date().toLocaleString(),
    metadata: {
      generatedBy: 'ESG Reporter',
      version: '1.0',
      status: `${report.completeness || 0}% Complete`
    },
    sections: [
      {
        title: 'Executive Summary',
        content: report.narrative || 'No narrative available'
      },
      {
        title: 'Environmental Metrics',
        content: report.metrics?.environmental 
          ? Object.entries(report.metrics.environmental).map(([key, value]) => 
              `${key}: ${value}`
            )
          : ['No environmental data available']
      },
      {
        title: 'Social Metrics',
        content: report.metrics?.social 
          ? Object.entries(report.metrics.social).map(([key, value]) => 
              `${key}: ${value}`
            )
          : ['No social data available']
      },
      {
        title: 'Governance Metrics',
        content: report.metrics?.governance 
          ? Object.entries(report.metrics.governance).map(([key, value]) => 
              `${key}: ${value}`
            )
          : ['No governance data available']
      },
      {
        title: 'CSRD Compliance',
        content: [
          `Completeness: ${report.completeness || 0}%`,
          `Report Period: ${report.period || 'Not specified'}`,
          `Last Updated: ${new Date(report.created_at).toLocaleString()}`
        ]
      }
    ]
  }
}
